# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f723536a9243d5b33a7079595a525b46ea064b362355ed740610eea7193be0b56a8e03d35713b9dcf708312fee007cb11072bf01412ab71b2ee7949c4b9d852e

test:
  secret_key_base: ba4874b019259ff846f828ae43abb99e6281d58a50dc743e91b756d6dce95a30eabd3c5d1f31b56eac7e636a20338201f7d82ab5e5fa9f2622251d5a4fc82efc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
